name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: crystaldata/numci

    steps:
    - uses: actions/checkout@v4

    - name: Install shards
      run: shards install --ignore-crystal-version

    - name: Run tests
      run: |
        crystal spec -v
